# -*- coding: utf-8 -*-
"""K-means

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fal7bvllzgETskZOKidXnOycn0qFoa5S

Import
"""

import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt

"""Select random points"""

def init_centroids(X, k):
    m, n = X.shape
    centroids = np.zeros((k, n))
    index = np.random.randint(0, m, k)
    
    for i in range(k):
        centroids[i,:] = X[index[i],:]
    
    return centroids

"""Centroid function"""

def find_closest_centroids(X, centroids):
    m = X.shape[0]
    k = centroids.shape[0]
    idx = np.zeros(m)
    
    
    for i in range(m):
        min_dist = 1000000
        for j in range(k):
            dist = np.sum((X[i,:] - centroids[j,:]) ** 2)
            if dist < min_dist:
                min_dist = dist
                idx[i] = j
    
    return idx

"""Centroid maker"""

def compute_centroids(X, index, k):
    m, n = X.shape
    centroids = np.zeros((k, n))
    
    for i in range(k):
        indices = np.where(index == i)
        centroids[i,:] = (np.sum(X[indices,:], axis=1) / len(indices[0])).ravel()
    
    return centroids

def k_means(X, k, max_iter):
    m, n = X.shape
    index = np.zeros(m)
    centroids =  init_centroids(X, k)

    for i in range(max_iter):
        index = find_closest_centroids(X, centroids)
        centroids = compute_centroids(X, index, k)
    
    return index, centroids

"""Load data"""

from google.colab import files
data_to_load = files.upload()

data = loadmat('ex7data2.mat')
print(data)
print(data['X'].shape)

"""Classigy points"""

X = data['X']
initail_centroids= init_centroids(X,3)
print(initail_centroids)

idx= find_closest_centroids(X, initail_centroids)
idx

c= compute_centroids(X, idx, 3)
print(c)

#Run k_means
index, centroids = k_means(X, 3, 10)


#Graph
cluster1 = X[np.where(index == 0)[0],:]
cluster2 = X[np.where(index == 1)[0],:]
cluster3 = X[np.where(index == 2)[0],:]

fig, ax = plt.subplots(figsize=(9,6))
ax.scatter(cluster1[:,0], cluster1[:,1], s=30, color='r', label='Cluster 1')
ax.scatter(centroids[0,0],centroids[0,1],s=300, color='r')

ax.scatter(cluster2[:,0], cluster2[:,1], s=30, color='g', label='Cluster 2')
ax.scatter(centroids[1,0],centroids[1,1],s=300, color='g')

ax.scatter(cluster3[:,0], cluster3[:,1], s=30, color='b', label='Cluster 3')
ax.scatter(centroids[2,0],centroids[2,1],s=300, color='b')
ax.legend()